version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: biz_service_frontend
    container_name: biz_service_frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=development
    command: npm run dev
